doc/sly.texi
* sly.texi: Update keymap documentation to reflect changes in keymaps
introduced in commit ec192073
FWIW I'd prefer the ```~``` (common-lisp-hyperspec-format) and ```#``` (common-lisp-hyperspec-lookup-reader-macro) to not need that las Ctrl in the default layout as it is easier to press in an english layout keyboard.
=> Update keymap documentation

contrib/sly-mrepl.el, doc/sly.texi
I spotted a typo and attempted to tackle a seemingly low hanging fruit in the documentation. Hope it helps
=> Add keymap information on mrepl to the manual

.gitignore
Another temporary file created when compiling a file with ABCL is <file-name-with-extension>-tmp, but that seemed generic enough
=> .gitignore: Ignore ABCL uncompressed FASLs

contrib/sly-mrepl.el
* sly-mrepl.el (sly-mrepl--highlight-backreferences-maybe): use cl-first and cl-rest
When trying out #v<n> I found that the first time, a post-command-hook
error would fire to the effect that rest was an unknown function, after
which the #v mechanism was slightly broken. I was using emacs -q in 
order to isolate any problems I was having with my config, consequently 
I had not loaded cl-lib. I tracked it down to sly-mrepl.el.
=> Fix post-command-hook error after using #v

slynk/slynk.lisp
By using the Decimal directive we force numbers to be printed as decimal,
ignoring the value of *print-base*, using the Aesthetic directive prints the
number respecting *print-base*.
* slynk/slynk.lisp (present-number-considering-alist): Use Aesthetic directive
instead the Decimal directive
<hr />
Btw, I am aware that sly provides a more complete way to configure how to print numbers in `SLYNK:*ECHO-NUMBER-ALIST*` and `SLYNK:*PRESENT-NUMBER-ALIST*` and they seem better suited for a long term need, for instance they can present multiple information about the number at once. But I don't think that providing this mechanism should ignore the language built-in ones.
=> Don't force numbers to be printed as decimal

sly.el
=> Only load bundled hyperspec if no copy is on the load-path

slynk/slynk.lisp
- slynk.lisp (_slyfuns_): New variable
(defslyfun): Save function definition in _slyfuns_
Using a hash-table instead of a list to avoid duplicate entries when
redefining a defslyfun
Related #94
=> Track defined slyfuns in *slyfuns*

slynk/metering.lisp, slynk/xref.lisp
No need to set package local variables to a wrong value. This should have been part of commit 440806f6 but that train has sailed :smile_cat:
=> Remove package from file local variables

lib/sly-parse.el
The narrow-to-region optimization in sly-parse-form-upto-point can
fool the use of syntax-ppss added in a previous fix. So call
syntax-ppss before narrowing the buffer.
Another option would be to forego the optimization. And yet another
option would be to use syntax-ppss exclusively.
* lib/sly-parse.el (sly-parse-form-upto-point): Call syntax-ppss
before narrowing buffer.
=> Fix a minor problem preventing sly-autodoc in some conditions

contrib/sly-package-fu.el, sly.el
This function is bound to C-c i by default, and using it, you can easily simplify
your code by moving package prefixes into the defpackage form.
Here is a demo:
https://youtu.be/pZ72_hI4Tcw
=> Added function sly-import-symbol-at-point to add import-from into thecurrent defpackage form

sly.el
Per #160.
* sly.el (sly-db-focus-debugger): New option to control how debugger is displayed.
(sly-db-setup): Delegate how the buffer is displayed.
(sly-db-should-focus-debugger-p): New helper.
(sly-db-display-debugger): New helper.
=> Add an option to prevent popping up the debugger.

slynk/slynk-completion.lisp
I happened to be using ABCL, and it raised an error every time I tried to complete a keyword.
I looked into the Slynk side and found the following lines in flex-completions:
```
(loop with (external internal)
= (multiple-value-list (qualified-matching pattern package))
```
The problem is that, when a symbol bails with a colon, `qualified-matching` bails early with `unless`, and only returns one value. ABCL's loop implementation is strict enough to care.
I changed `qualified-matching` so it would always return two values, and fixed some strange indentation in the docstring while I was in there.
=> Fix completion of symbols that start with a colon.

NEWS.md, lib/sly-messages.el, sly.el
A new customization variable `sly-command-switch-to-existing-lisp' is
introduced.
* NEWS.md: Mention `sly-command-switch-to-existing-lisp'
* sly.el (sly--when-let*): New macro.
(sly-command-switch-to-existing-lisp): New defcustom.
(sly): Use it.
(sly-prompt-for-connection): Accept more optional args.
(sly-auto-select-connection): Move up here.
* lib/sly-messages.el (sly-completing-read-no-match-label): New
variable.
(sly-ido-completing-read): Use it.
=> Friendlier M-x sly

contrib/sly-package-fu.el
Without this fix, an attempt to use sly-export-symbol-at-point produces an error in a freshly started sly (if 'cl has not been required yet).
=> bug fix: replace EQUALP with CL-EQUALP in elisp code

slynk/slynk.lisp
The EMACS-INSPECT method that specialized on HASH-TABLE tries to order
the contents of the hash-table before to present them in order. However
it incorrectly applies the function < if the contents are NUMBERs. Only =
and /= are defined for NUMBERS. < and the other comparison functions
apply only to REALs. Because this feature is an extra nicety fix the bug
by not ordering the contents in the presences of COMPLEX numbers.
To reproduce the bug inspect the hash table from return by
(let ((ht (make-hash-table)))
(setf (gethash #C(0 1) ht) t
(gethash #C(0 2) ht) t)
ht)
=> Fix Hash Table Inspector with Complex Numbers as keys

slynk/slynk.lisp
=> Bind `*macroexpand-printer-bindings*` during print, not macroexpansion

contrib/sly-package-fu.el
* contrib/sly-package-fu.el (uiop:define-package): Use a
reasonable indentation spec.
=> Fix #243: indent UIOP:DEFINE-PACKAGE like CL:DEFPACKAGE

doc/sly.texi
=> doc/sly.texi: Fix "becasue" typo.

contrib/slynk-mrepl.lisp, slynk/slynk.lisp
Resolve #288 
Defines `-` inside the running form, instead of leaving it free, but only for a slynk `simple-repl`. I had some help from `bike` and `pjb` on `#lisp` for this one.
I'm not sure what code is getting run for a normal REPL.
=> Ensure - is defined within the running form.

sly.el
Was going through and documenting prefix and negative prefix arguments.
`C-u M-x sly-switch-to-most-recent` is documented to prompt for the mode, but actually behaves the same as no prefix argument. This is simply due to an incorrectly named variable.
=> Prefix argument to sly-switch-to-most-recent fails to prompt.

contrib/sly-mrepl.el
I request this feature where `quit` exists and is the same as `sayoonara`.
=> Alias "quit lisp" as sayoonara

sly.el
If you know what it is actually meant for, then it could be good to fix it instead of removing it. I can't tell what it is actually meant to do though.
Since it tries to run a function that is not defined at all, maybe just remove it as is done here.
=> Remove the broken prefix argument for sly-db-eval-in-frame

doc/sly.texi, sly.el
Some functions have undocumented prefix arguments, and the xref commands lack an elisp docstring.
=> Document xref functions, and some functions with prefix arguments

sly.el
Reverts #330 
Unfortunately my proposed fix for #330 was a bit too simplistic and a proper fix will be a little more involved than just the comparison I proposed (see slime/slime#571).
=> Revert "Fix #330: only insert "--more--" button in SLY DB when actually needed"

contrib/sly-mrepl.el
Backreference messages sometimes contain "%" symbols, and would cause
`sly-mrepl--highlight-backreferences-maybe' to throw an error. This is a simple fix to escape the message.
=> Escaping for backreference messages.

contrib/sly-mrepl.el
I edit lisp codes in org file with https://github.com/polymode/poly-org, sometimes `previous-single-property-change` will return nil value when guess package.
=> add safe check for package guess.

contrib/sly-mrepl.el
=> Allow naming a new inspector when inspecting a button in the MREPL

lib/sly-cl-indent.el, test/sly-cl-indent-test.txt
the regexp in sly-cl-indent.el which matched `in` loop keyword clauses was mistakenly matching `initially` clauses, causing ugliness like 
```lisp
(loop for x in y
initially
(format t "I'm too far away!")
...)
```
now the regexps are terminated with `\\_>` which prevents the false positive. the old one also didn't match `upfrom` , `downto` , `from` and the like (author forgot to escape the group) so i used `regexp-opt` to avoid thinkos like that.
=> Fix #471: Make loop keyword indentation regexps more precise

sly.el
* sly.el (sly-push-definition-stack): Inserting directly into
`find-tag-marker-ring` is obsolete since emacs 25.1.  As of emacs 29 sly no
longer is able to jump back and forth between definition and usage with `M-.`
and `M-,`.  As a precaution for backwards compatibility, we use
`xref-push-marker-stack` only when it is bound.
=> Use xref-push-marker-stack when available

slynk/backend/clasp.lisp
This catches up with some recent changes to Clasp and some fixes made to SLIME which were not made here at the same time.
- Replace TMP host with EXT:TEMPORARY-DIRECTORY when available
- Translate logical pathnames in source references
- Change va-list to vaslist and renamed core package
- Clasp uses the USE-VALUE restart to cycle ports
=> clasp: Update for changes in logical hosts and some function names

.gitignore, slynk/backend/abcl.lisp, slynk/slynk.asd
This PR fixes the issues with the ABCL backend described in https://github.com/joaotavora/sly/issues/425, as well as several other bugs and issues such as https://github.com/slime/slime/issues/649, and removes a nonfunctional feature or two.
Unlike https://github.com/joaotavora/sly/pull/449, this PR does not introduce any new files; though the load order is adjusted slightly to allow the backend to make use of `slynk-match`, the rest of the load order is untouched and the other uses of functions that are not defined at the time the backend is loaded are dealt with using a hack to read the symbol at runtime. This hack is as constrained as possible so it shouldn't spread too far and should be easy to replace.
I've tried to break this out into relatively sensical commits with more details …
=> Fix the ABCL Backend

contrib/sly-mrepl.el
This allows `commandp` to return T for `sly-mrepl`, even when the library is not yet loaded. Note that other top-level functions in Sly are already autoloaded, like the `sly` function itself, so there is precedent.
=> Autoload `sly-mrepl`

sly.el
* sly.el (sly-quit-connection-at-point): Invoke function with a floating-point argument.
=> Fix obsolete invocation of 'sit-for'

lib/sly-buttons.el
I ran into the issue described in https://github.com/joaotavora/sly/issues/466 and this seems to fix it.  This might be a nicer fix than the existing PR, given that it might have unintended side-effects to change or remove `sly-db-frame-map`'s parent keymap.
=> sly-button-define-part-action: Pass 'no-error to ‘sly-button-at’

slynk/slynk.lisp
Closes #470.
My use-case is as follows: Nyxt depends on `slynk/indentation` and `lass`, which in turn calls `indent:define-indentation` from `trivial-indent`. Without this fix, it would raise the error below.
```lisp
debugger invoked on a SB-KERNEL:CASE-FAILURE @5436DF2E in thread
#<THREAD tid=19916 "main thread" RUNNING {10017401B3}>:
NIL fell through ETYPECASE expression.
Wanted one of (SLYNK::SINGLETHREADED-CONNECTION
SLYNK::MULTITHREADED-CONNECTION).
Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
restarts (invokable by number or by possibly-abbreviated name):
0: [TRY-RECOMPILING              ] Recompile special and try loading it again
1: [RETRY                        ] Retry
loading FASL for #<CL-SOURCE-FILE "lass" "special">.
2: [ACCEPT                       ] …
```
=> Fix #470: Handle case when there is no emacs-connection.

sly.el
Currently, SLY interactively prompts the user at load time if SLIME already loaded, to ask whether to replace SLIME in `lisp-mode-hook`.  This change offers a new flag, `sly-ask-replace-slime`, to control the prompting behavior.  It defaults to `t`, which preserves the current behavior.  But if you put `(setq sly-ask-replace-slime nil)` in your Emacs initialization before loading SLY, then if SLY finds that SLIME is already loaded, SLY will just replace it without prompting.
Motivation:
Someone might have SLIME automatically loaded in some environments, SLY in others, and both in still others.  For example, I have this in my .emacs file:
```elisp
(setq sly-ask-replace-slime nil)  ;; this line is new -- assumes this PR
(dolist (lib (list "slime" "sly"))
(let ((lib-path (expand-file-name …
```
=> Add option to replace SLIME on load w/o prompting

lib/sly-completion.el
Completion when jumping to source of a symbol was referencing an old completion style that no longer exists.
=> Fix read-symbol-name after recent completion changes

sly.el
Seems like that was what was intended, but it ended up only testing for `interactive` twice instead.
=> sly-sexp-at-point: error only with both `interactive` and `errorp`

lib/hyperspec.el
The file:// URL example in the common-lisp-hyperspec-root docstring was missing a slash.
=> Fix file:// URL example in common-lisp-hyperspec-root docstring
